name: docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    env:
      DOCS_GA_ID: G-CTB8FQ7VMW
      NODE_VERSION: '20'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      # - name: Install dependencies
      #   run: pnpm install --frozen-lockfile

      # - name: Build documentation site
      #   run: pnpm docs:build

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_SCRIPT: pnpm install --frozen-lockfile && pnpm docs:build
          BUILD_DIR: docs/.vuepress/dist/

      # - name: Deploy to GitHub Pages
      #   uses: crazy-max/ghaction-github-pages@v4
      #   with:
      #     target_branch: gh-pages
      #     build_dir: docs/.vuepress/dist
      #     fqdn: study.guowei.fun
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
